#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
# Import libraries
import numpy as np
from datetime import datetime, timedelta


#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
# Check version of numpy
print(np.__version__)

1.26.2


#### 3. Create a null vector of size 10 (★☆☆)


In [13]:
# Create a null vector of size 10
null_vector = np.zeros(10)

print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)


In [14]:
# Find the memory size of the array
memory_size = null_vector.nbytes

print("Memory size of the array:", memory_size, "bytes")

Memory size of the array: 80 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)


In [ ]:
python -m pydoc numpy.add

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)


In [5]:
# Create a null vector of size 10
null_vector = np.zeros(10)

# Assign 1 to the fifth element (index 4, since indexing starts from 0)
null_vector[4] = 1

print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)


In [6]:
# Create a vector with values ranging from 10 to 49
vector = np.arange(10, 50)

print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [7]:
# Create a vector with values ranging from 10 to 49
vector = np.arange(10, 50)

# Reverse the vector
reversed_vector = vector[::-1]

print(reversed_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [8]:
# Create a vector with values ranging from 0 to 8
values = np.arange(9)

# Reshape the vector into a 3x3 matrix
matrix = values.reshape(3, 3)

print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [3]:
# Define the array
arr = np.array([1, 2, 0, 0, 4, 0])

# Find the indices of non-zero elements
indices = np.nonzero(arr)

print(indices)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [4]:
# Create a 3x3 identity matrix
identity_matrix = np.eye(3)

print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [5]:
# Create a 3x3x3 array with random values
random_array = np.random.random((3, 3, 3))

print(random_array)

[[[0.99779468 0.08833564 0.38837869]
  [0.86875295 0.80056094 0.74114665]
  [0.8217505  0.64917543 0.77469958]]

 [[0.77200978 0.70975654 0.87468841]
  [0.95425678 0.49664782 0.61496489]
  [0.42261108 0.2373618  0.31294906]]

 [[0.25836922 0.76586375 0.94941596]
  [0.6540722  0.59268556 0.59736153]
  [0.50586248 0.39216966 0.19930711]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [6]:
# Create a 10x10 array with random values
random_array = np.random.random((10, 10))

# Find the minimum and maximum values
min_value = np.min(random_array)
max_value = np.max(random_array)

print("Minimum value:", min_value)
print("Maximum value:", max_value)

Minimum value: 0.012385921668583766
Maximum value: 0.9979431617686895


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [7]:
# Create a random vector of size 30
random_vector = np.random.random(30)

# Find the mean value
mean_value = np.mean(random_vector)

print("Mean value:", mean_value)

Mean value: 0.5504029687477323


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [9]:
# Define the shape of the 2D array
rows, cols = 7, 5

# Create a 2D array filled with zeros
array = np.zeros((rows, cols))

# Set the border elements to 1
array[0, :] = 1  # Top row
array[-1, :] = 1  # Bottom row
array[:, 0] = 1  # Left column
array[:, -1] = 1  # Right column

print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [10]:
# Example existing array
existing_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

# Get the shape of the existing array
rows, cols = existing_array.shape

# Define the size of the border to add
border_size = 1

# Create a new array with zeros and the appropriate size
new_array = np.zeros((rows + 2 * border_size, cols + 2 * border_size))

# Copy the existing array into the center of the new array
new_array[border_size:rows+border_size, border_size:cols+border_size] = existing_array

print(new_array)

[[0. 0. 0. 0. 0.]
 [0. 1. 2. 3. 0.]
 [0. 4. 5. 6. 0.]
 [0. 7. 8. 9. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan = nan
np.nan == np.nan = False
np.inf > np.nan = False
np.nan - np.nan = nan
np.nan in set([np.nan]) = True
0.3 == 3 * 0.1 = False
```


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [20]:
# Create a 5x5 matrix filled with zeros
matrix = np.zeros((5, 5))

# Define the values to place below the diagonal
values = [1, 2, 3, 4]

# Set the values just below the diagonal
for i, value in enumerate(values):
    matrix[i+1, i] = value

print(matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [21]:
# Create an 8x8 matrix filled with zeros
matrix = np.zeros((8, 8), dtype=int)

# Assign alternate values (0 and 1) to alternate rows and columns
matrix[1::2, ::2] = 1  # Rows 1, 3, 5, 7, Columns 0, 2, 4, 6
matrix[::2, 1::2] = 1  # Rows 0, 2, 4, 6, Columns 1, 3, 5, 7

print(matrix)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [22]:
# Define the shape of the array
shape = (6, 7, 8)

# Find the indices of the 100th element
indices = np.unravel_index(99, shape)

print("Indices (x, y, z) of the 100th element:", indices)

Indices (x, y, z) of the 100th element: (1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [23]:
# Create a 2x2 checkerboard pattern
checkerboard = np.array([[0, 1], [1, 0]])

# Use tile function to repeat the pattern to create an 8x8 matrix
checkerboard_8x8 = np.tile(checkerboard, (4, 4))

print(checkerboard_8x8)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [24]:
# Create a 5x5 random matrix
matrix = np.random.random((5, 5))

# Calculate the mean and standard deviation of the matrix
mean = np.mean(matrix)
std_dev = np.std(matrix)

# Normalize the matrix
normalized_matrix = (matrix - mean) / std_dev

print("Original Matrix:")
print(matrix)
print("\nNormalized Matrix:")
print(normalized_matrix)

Original Matrix:
[[0.84385226 0.12815049 0.22805669 0.42831618 0.82306305]
 [0.41925023 0.77156786 0.43331991 0.67419839 0.14707416]
 [0.74607737 0.00873546 0.00643697 0.64935321 0.88928044]
 [0.11669372 0.34714801 0.14040371 0.71365048 0.03550355]
 [0.27349522 0.73707641 0.94187851 0.26765774 0.00795224]]

Normalized Matrix:
[[ 1.32104334 -0.9697654  -0.64998697 -0.00899904  1.25450151]
 [-0.03801722  1.08967637  0.00701684  0.77801746 -0.90919476]
 [ 1.00808675 -1.35198744 -1.35934442  0.69849336  1.46644924]
 [-1.00643609 -0.26880104 -0.93054546  0.90429518 -1.2663085 ]
 [-0.50454794  0.97927661  1.63480445 -0.52323244 -1.35449437]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)


In [25]:
# Define the custom dtype for RGBA color
color_dtype = np.dtype([('R', np.uint8),   # Red component
                        ('G', np.uint8),   # Green component
                        ('B', np.uint8),   # Blue component
                        ('A', np.uint8)])  # Alpha component

# Create a color using the custom dtype
color = np.array((255, 0, 0, 255), dtype=color_dtype)

print("RGBA Color:")
print(color)

RGBA Color:
(255, 0, 0, 255)


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [26]:
# Create a 5x3 matrix
matrix1 = np.random.random((5, 3))

# Create a 3x2 matrix
matrix2 = np.random.random((3, 2))

# Multiply the matrices
result = np.dot(matrix1, matrix2)

print("Resulting Matrix:")
print(result)

Resulting Matrix:
[[0.52445287 0.95481423]
 [0.32419711 0.38890865]
 [0.66586139 1.20303171]
 [0.41001965 0.75686865]
 [0.46236983 0.81202453]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [27]:
# Create a 1D array
array = np.array([1, 4, 6, 9, 3, 2, 7, 5, 8])

# Negate elements between 3 and 8 (inclusive)
array[(array >= 3) & (array <= 8)] *= -1

print("Modified Array:")
print(array)

Modified Array:
[ 1 -4 -6  9 -3  2 -7 -5 -8]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1)) = 9 because the in-built sum function starts summing from -1 to 4.
from numpy import *
print(sum(range(5),-1)) = 10 because -1 specifies the axis along which the summation is done which is the last axis. In this case range(5) is a 1D.
```


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

Z**Z: This expression raises each element of vector Z to the power of itself. It's legal in Python.

2 << Z >> 2: This expression performs bitwise left shift (<<) of 2 by each element of vector Z, and then performs bitwise right shift (>>) of the result by 2. It's legal in Python.

Z <- Z: This expression compares each element of vector Z with the negation of itself. It's legal in Python.

1j*Z: This expression multiplies each element of vector Z by the imaginary unit 1j. It's legal in Python.

Z/1/1: This expression divides each element of vector Z by 1 and then divides the result by 1 again. It's legal in Python.

Z<Z>Z: This expression is not legal. It tries to compare each element of vector Z with itself (Z < Z), and then compare the result with Z, which is not syntactically valid in Python.

So, the legal expressions are:

Z**Z

2 << Z >> 2

Z <- Z

1j*Z

Z/1/1


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

np.array(0) / np.array(0): This expression divides zero by zero. In NumPy, this results in a runtime warning, and the result is nan (not a number).

np.array(0) // np.array(0): This expression performs floor division of zero by zero. In NumPy, this also results in a runtime warning, and the result is 0.

np.array([np.nan]).astype(int).astype(float): This expression first creates a NumPy array containing a NaN (Not a Number) value, then converts it to an integer type using astype(int). Since NaN cannot be represented as an integer, it's converted to 0. Finally, the array is converted back to a float type using astype(float), resulting in an array containing [0.].

So, the results are:

np.array(0) / np.array(0): nan

np.array(0) // np.array(0): 0

np.array([np.nan]).astype(int).astype(float): [0.]

#### 29. How to round away from zero a float array ? (★☆☆)


In [33]:
# Example float array
float_array = np.array([-1.5, 2.7, -3.4, 4.8])

# Round away from zero by rounding up (ceil) the positive numbers and rounding down (floor) the negative numbers
rounded_array = np.sign(float_array) * np.ceil(np.abs(float_array))

print("Original Float Array:", float_array)
print("Rounded Away from Zero Array:", rounded_array)

Original Float Array: [-1.5  2.7 -3.4  4.8]
Rounded Away from Zero Array: [-2.  3. -4.  5.]


#### 30. How to find common values between two arrays? (★☆☆)


In [34]:
# Example arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

# Find common values between the two arrays
common_values = np.intersect1d(array1, array2)

print("Common Values:", common_values)

Common Values: [3 4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)


In [35]:
import warnings

# Ignore all NumPy warnings
warnings.filterwarnings('ignore', category=np.VisibleDeprecationWarning)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

No, the expression is not true.

In NumPy, np.sqrt(-1) returns a complex number representing the square root of -1 (1j), while np.emath.sqrt(-1) returns a complex number with a warning indicating that it's returning the principal square root of a negative number (1j).

However, both expressions return the same complex number 1j, but np.emath.sqrt(-1) provides additional warning information. Therefore, the equality check np.sqrt(-1) == np.emath.sqrt(-1) evaluates to True.

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)


In [37]:

# Get today's date
today = datetime.today().date()

# Get yesterday's date
yesterday = today - timedelta(days=1)

# Get tomorrow's date
tomorrow = today + timedelta(days=1)

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2024-02-06
Today: 2024-02-07
Tomorrow: 2024-02-08


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)


In [3]:
# Define the start date (July 1, 2016)
start_date = datetime(2016, 7, 1)

# Define the end date (July 31, 2016)
end_date = datetime(2016, 7, 31)

# Generate all the dates for the month of July 2016
dates_in_july_2016 = [start_date + timedelta(days=x) for x in range((end_date - start_date).days + 1)]

# Print the dates
for date in dates_in_july_2016:
    print(date.date())

2016-07-01
2016-07-02
2016-07-03
2016-07-04
2016-07-05
2016-07-06
2016-07-07
2016-07-08
2016-07-09
2016-07-10
2016-07-11
2016-07-12
2016-07-13
2016-07-14
2016-07-15
2016-07-16
2016-07-17
2016-07-18
2016-07-19
2016-07-20
2016-07-21
2016-07-22
2016-07-23
2016-07-24
2016-07-25
2016-07-26
2016-07-27
2016-07-28
2016-07-29
2016-07-30
2016-07-31


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)


In [6]:
# Example arrays A and B
A = np.array([1, 2, 3], dtype=float)  # Convert A to float
B = np.array([4, 5, 6])

# Compute ((A+B)*(-A/2)) in place
np.add(A, B, out=A)     # A += B
np.negative(A, out=A)   # A *= -1
np.divide(A, 2, out=A)  # A /= 2

result = np.floor(A)  # Convert the result to integers using np.floor

print("Result:", result)

Result: [-3. -4. -5.]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)


In [7]:
# Create a random array of positive numbers
random_array = np.random.rand(5) * 10  # Random numbers between 0 and 10

# Method 1: Using numpy.floor
integer_part_floor = np.floor(random_array)

# Method 2: Using numpy.trunc
integer_part_trunc = np.trunc(random_array)

# Method 3: Using integer casting (numpy.astype(int))
integer_part_casting = random_array.astype(int)

# Method 4: Using numpy.int_
integer_part_int = np.int_(random_array)

print("Random Array:", random_array)
print("Integer Part (Floor):", integer_part_floor)
print("Integer Part (Trunc):", integer_part_trunc)
print("Integer Part (Casting):", integer_part_casting)
print("Integer Part (int_):", integer_part_int)

Random Array: [2.84983875 9.39948318 8.33059177 3.01386385 5.83742977]
Integer Part (Floor): [2. 9. 8. 3. 5.]
Integer Part (Trunc): [2. 9. 8. 3. 5.]
Integer Part (Casting): [2 9 8 3 5]
Integer Part (int_): [2 9 8 3 5]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)


In [8]:
# Create a 5x5 matrix with row values ranging from 0 to 4
matrix = np.arange(5).reshape(1, -1) + np.zeros((5, 5), dtype=int)

print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)


In [9]:
# Define a generator function to generate 10 integers
def integer_generator():
    for i in range(10):
        yield i

# Create an array from the generator function
array = np.fromiter(integer_generator(), dtype=int)

print("Array generated from the generator function:")
print(array)

Array generated from the generator function:
[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)


In [10]:
# Create a vector of size 10 with values ranging from 0 to 1 (both excluded)
vector = np.linspace(0, 1, 12)[1:-1]

print("Vector with values ranging from 0 to 1 (both excluded):")
print(vector)

Vector with values ranging from 0 to 1 (both excluded):
[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)


In [11]:
# Create a random vector of size 10
random_vector = np.random.rand(10)

# Sort the random vector
sorted_vector = np.sort(random_vector)

print("Random Vector:")
print(random_vector)
print("\nSorted Vector:")
print(sorted_vector)

Random Vector:
[0.65359083 0.71288318 0.39665143 0.84190102 0.0710288  0.27552306
 0.43600556 0.20194343 0.7720694  0.11847143]

Sorted Vector:
[0.0710288  0.11847143 0.20194343 0.27552306 0.39665143 0.43600556
 0.65359083 0.71288318 0.7720694  0.84190102]


#### 41. How to sum a small array faster than np.sum? (★★☆)


In [12]:
# Create a random vector of size 10
random_vector = np.random.rand(10)

# Sort the random vector
sorted_vector = np.sort(random_vector)

print("Random Vector:")
print(random_vector)
print("\nSorted Vector:")
print(sorted_vector)

Random Vector:
[0.88074584 0.44055372 0.12934256 0.84399697 0.57756575 0.7629271
 0.70629224 0.04979876 0.94682359 0.79341998]

Sorted Vector:
[0.04979876 0.12934256 0.44055372 0.57756575 0.70629224 0.7629271
 0.79341998 0.84399697 0.88074584 0.94682359]


#### 42. Consider two random array A and B, check if they are equal (★★☆)


In [13]:
# Create two random arrays A and B
A = np.random.rand(5)
B = np.random.rand(5)

# Check if arrays A and B are equal
are_equal = np.array_equal(A, B)

print("Arrays A and B are equal:", are_equal)

Arrays A and B are equal: False


#### 43. Make an array immutable (read-only) (★★☆)


In [14]:
# Create an array
array = np.array([1, 2, 3, 4, 5])

# Make the array immutable (read-only)
array.flags.writeable = False

# Try to modify the array (this will raise an error)
try:
    array[0] = 10
except ValueError as e:
    print("Error:", e)

Error: assignment destination is read-only


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)


In [15]:
# Create a random 10x2 matrix representing cartesian coordinates
cartesian_coordinates = np.random.rand(10, 2)

# Extract x and y coordinates
x = cartesian_coordinates[:, 0]
y = cartesian_coordinates[:, 1]

# Convert cartesian coordinates to polar coordinates
r = np.hypot(x, y)
theta = np.arctan2(y, x)

# Combine r and theta to get polar coordinates
polar_coordinates = np.column_stack((r, theta))

print("Cartesian Coordinates:")
print(cartesian_coordinates)
print("\nPolar Coordinates:")
print(polar_coordinates)


Cartesian Coordinates:
[[0.78932955 0.85173678]
 [0.81875664 0.72839663]
 [0.22757681 0.03790853]
 [0.32377062 0.07408615]
 [0.40072167 0.20085401]
 [0.44637493 0.47641619]
 [0.64820524 0.02004811]
 [0.16336107 0.99062954]
 [0.27184457 0.21213644]
 [0.58788841 0.64803122]]

Polar Coordinates:
[[1.1612479  0.82340831]
 [1.09586682 0.72706039]
 [0.23071251 0.16505916]
 [0.33213878 0.22495019]
 [0.44824122 0.4646317 ]
 [0.65285754 0.81794145]
 [0.6485152  0.03091879]
 [1.00400883 1.40736091]
 [0.34482074 0.66264964]
 [0.87496128 0.8340222 ]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)


In [16]:
# Create a random vector of size 10
random_vector = np.random.rand(10)

# Find the index of the maximum value
max_index = np.argmax(random_vector)

# Replace the maximum value by 0
random_vector[max_index] = 0

print("Random Vector with Maximum Value Replaced by 0:")
print(random_vector)


Random Vector with Maximum Value Replaced by 0:
[0.00412451 0.64527285 0.29135602 0.48761764 0.04625653 0.4562283
 0.26959986 0.         0.61696773 0.86634277]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)


In [17]:
# Define the number of points in each dimension
num_points = 5

# Create arrays representing the x and y coordinates
x_coordinates = np.linspace(0, 1, num_points)
y_coordinates = np.linspace(0, 1, num_points)

# Create a meshgrid from the x and y coordinates
x_mesh, y_mesh = np.meshgrid(x_coordinates, y_coordinates)

# Create a structured array with x and y coordinates
structured_array = np.zeros((num_points, num_points), dtype=[('x', float), ('y', float)])
structured_array['x'] = x_mesh
structured_array['y'] = y_mesh

print("Structured Array with x and y Coordinates:")
print(structured_array)


Structured Array with x and y Coordinates:
[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)


In [18]:
# Example arrays X and Y
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

# Construct the Cauchy matrix C
C = 1 / (X[:, np.newaxis] - Y)

print("Cauchy Matrix C:")
print(C)

Cauchy Matrix C:
[[-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)


In [22]:
# Print the minimum and maximum representable values for each integer scalar type
print("Integer scalar types:")
for dtype in [np.int8, np.int16, np.int32, np.int64]:
    info = np.iinfo(dtype)
    print(f"{dtype.__name__}: Min = {info.min}, Max = {info.max}")

# Print the minimum and maximum representable values for each floating-point scalar type
print("\nFloating-point scalar types:")
for dtype in [np.float32, np.float64]:
    info = np.finfo(dtype)
    print(f"{dtype.__name__}: Min = {info.min}, Max = {info.max}")

# Check if float128 is available
if hasattr(np, 'float128'):
    info = np.finfo(np.float128)
    print(f"np.float128: Min = {info.min}, Max = {info.max}")
else:
    print("np.float128 is not available on this system.")

Integer scalar types:
int8: Min = -128, Max = 127
int16: Min = -32768, Max = 32767
int32: Min = -2147483648, Max = 2147483647
int64: Min = -9223372036854775808, Max = 9223372036854775807

Floating-point scalar types:
float32: Min = -3.4028234663852886e+38, Max = 3.4028234663852886e+38
float64: Min = -1.7976931348623157e+308, Max = 1.7976931348623157e+308
np.float128 is not available on this system.


#### 49. How to print all the values of an array? (★★☆)


In [23]:
# Create an array
array = np.arange(25).reshape(5, 5)

# Print all the values of the array
np.set_printoptions(threshold=np.inf)  # Set threshold to display the entire array
print(array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)


In [24]:
# Create a vector
vector = np.array([1, 3, 5, 7, 9])

# Given scalar
scalar = 6

# Find the index of the closest value to the scalar
closest_index = np.argmin(np.abs(vector - scalar))

# Get the closest value
closest_value = vector[closest_index]

print("Vector:", vector)
print("Given Scalar:", scalar)
print("Closest Value:", closest_value)

Vector: [1 3 5 7 9]
Given Scalar: 6
Closest Value: 5


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)


In [25]:
# Define the data type for the structured array
dtype = np.dtype([('position', [('x', float), ('y', float)]), ('color', [('r', int), ('g', int), ('b', int)])])

# Create a structured array
structured_array = np.array([((1.0, 2.0), (255, 0, 0)), ((3.0, 4.0), (0, 255, 0)), ((5.0, 6.0), (0, 0, 255))], dtype=dtype)

print("Structured Array:")
print(structured_array)

Structured Array:
[((1., 2.), (255,   0,   0)) ((3., 4.), (  0, 255,   0))
 ((5., 6.), (  0,   0, 255))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)


In [26]:
# Create a random vector with shape (100, 2) representing coordinates
coordinates = np.random.rand(100, 2)

# Compute point-by-point distances
distances = np.linalg.norm(coordinates[:, np.newaxis, :] - coordinates[np.newaxis, :, :], axis=-1)

print("Point-by-point distances:")
print(distances)

Point-by-point distances:
[[0.         0.8599973  0.85841767 0.55560993 0.97602007 0.86446027
  0.43503908 0.49219068 0.83392054 0.62027892 0.80147102 0.21834633
  0.59130455 0.91385429 0.88543561 0.39310086 0.46237459 0.94075485
  0.51026109 0.93189868 0.21174468 0.20119966 0.43278639 0.3856235
  0.26501059 0.56867302 1.1950619  0.41140094 0.97699256 0.61846292
  1.28903537 0.22153876 0.49848168 0.86479591 0.9156552  0.47650684
  0.62834056 0.80825107 1.12892766 0.87837648 0.50013041 0.40162444
  0.67948103 0.91847377 0.76837265 0.41965424 0.50901973 0.84561415
  0.82212088 0.58589541 0.49416952 0.43313757 0.92838194 0.40007736
  0.69129411 0.08720291 0.38948012 0.84891974 0.57193206 0.80063411
  0.61974134 1.10459771 0.80039411 0.49311385 0.75420348 0.70010166
  1.08560333 0.78972252 0.52886664 0.24650685 0.94161184 0.88223992
  1.13028958 1.05093833 0.88311524 0.57044444 0.59561394 0.76113674
  0.87675022 0.60493328 0.66023387 1.11494097 1.00879879 0.59069295
  1.14715736 0.99231621

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?


In [28]:
# Create a float (32 bits) array
float_array = np.array([1.5, 2.7, 3.9], dtype=np.float32)

# Convert the float array into an integer (32 bits) array in place
float_array.view(dtype=np.int32)[:] = float_array

print("Integer (32 bits) array:", float_array)

Integer (32 bits) array: [1.e-45 3.e-45 4.e-45]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

You can read the provided file using NumPy's np.genfromtxt function, which is designed to read data from text files. Since the file contains missing values represented by empty cells, you can specify the delimiter parameter as , to indicate that the values are separated by commas, and use the filling_values parameter to specify the value to use for missing data. 

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)


In [29]:
# Create a NumPy array
array = np.array([[1, 2, 3], [4, 5, 6]])

# Iterate over the indices and values of the array
for index, value in np.ndenumerate(array):
    print("Index:", index, "Value:", value)

Index: (0, 0) Value: 1
Index: (0, 1) Value: 2
Index: (0, 2) Value: 3
Index: (1, 0) Value: 4
Index: (1, 1) Value: 5
Index: (1, 2) Value: 6


#### 56. Generate a generic 2D Gaussian-like array (★★☆)


In [30]:
def gaussian_2d(x, y, sigma):
    return np.exp(-(x**2 + y**2) / (2 * sigma**2))

# Define the size of the array and the standard deviation (sigma)
size = 5
sigma = 1

# Create a grid of coordinates
x, y = np.meshgrid(np.arange(-size, size+1), np.arange(-size, size+1))

# Generate the 2D Gaussian-like array
gaussian_array = gaussian_2d(x, y, sigma)

print("2D Gaussian-like array:")
print(gaussian_array)

2D Gaussian-like array:
[[1.38879439e-11 1.25015287e-09 4.13993772e-08 5.04347663e-07
  2.26032941e-06 3.72665317e-06 2.26032941e-06 5.04347663e-07
  4.13993772e-08 1.25015287e-09 1.38879439e-11]
 [1.25015287e-09 1.12535175e-07 3.72665317e-06 4.53999298e-05
  2.03468369e-04 3.35462628e-04 2.03468369e-04 4.53999298e-05
  3.72665317e-06 1.12535175e-07 1.25015287e-09]
 [4.13993772e-08 3.72665317e-06 1.23409804e-04 1.50343919e-03
  6.73794700e-03 1.11089965e-02 6.73794700e-03 1.50343919e-03
  1.23409804e-04 3.72665317e-06 4.13993772e-08]
 [5.04347663e-07 4.53999298e-05 1.50343919e-03 1.83156389e-02
  8.20849986e-02 1.35335283e-01 8.20849986e-02 1.83156389e-02
  1.50343919e-03 4.53999298e-05 5.04347663e-07]
 [2.26032941e-06 2.03468369e-04 6.73794700e-03 8.20849986e-02
  3.67879441e-01 6.06530660e-01 3.67879441e-01 8.20849986e-02
  6.73794700e-03 2.03468369e-04 2.26032941e-06]
 [3.72665317e-06 3.35462628e-04 1.11089965e-02 1.35335283e-01
  6.06530660e-01 1.00000000e+00 6.06530660e-01 1.35335

#### 57. How to randomly place p elements in a 2D array? (★★☆)


In [33]:
def randomly_place_elements(array, p, value):
    # Get the size of the array
    nrows, ncols = array.shape
    
    # Calculate the total number of elements in the array
    total_elements = nrows * ncols
    
    # Calculate the number of elements to randomly place
    num_elements_to_place = int(p * total_elements)
    
    # Generate random indices to place the elements
    random_indices = np.random.choice(total_elements, num_elements_to_place, replace=False)
    
    # Convert the 1D indices to 2D indices
    random_indices_2d = np.unravel_index(random_indices, (nrows, ncols))
    
    # Assign the value to the randomly chosen elements
    array[random_indices_2d] = value
    
    return array

# 2D array
array = np.zeros((5, 5), dtype=int)

# Number of elements to randomly place (as a fraction of the total number of elements)
p = 0.3

# Value to assign to the randomly placed elements
value = 1

# Randomly place elements in the array
array_with_elements = randomly_place_elements(array, p, value)

print("2D Array with Randomly Placed Elements:")
print(array_with_elements)


2D Array with Randomly Placed Elements:
[[0 1 0 0 1]
 [0 0 0 0 0]
 [0 0 1 0 1]
 [0 0 0 0 0]
 [1 0 1 0 1]]


#### 58. Subtract the mean of each row of a matrix (★★☆)


In [34]:
# Create a matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Compute the mean of each row
row_means = np.mean(matrix, axis=1, keepdims=True)

# Subtract the mean of each row from the corresponding row
result = matrix - row_means

print("Original Matrix:")
print(matrix)
print("\nResult after subtracting the mean of each row:")
print(result)


Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Result after subtracting the mean of each row:
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


#### 59. How to sort an array by the nth column? (★★☆)


In [35]:
# Create an array
array = np.array([[1, 4, 2], [3, 1, 6], [5, 2, 3]])

# Define the column index to sort by
n = 1

# Get the indices that would sort the array along the nth column
sorted_indices = np.argsort(array[:, n])

# Sort the array by the nth column
sorted_array = array[sorted_indices]

print("Original Array:")
print(array)
print("\nSorted Array by the nth column:")
print(sorted_array)

Original Array:
[[1 4 2]
 [3 1 6]
 [5 2 3]]

Sorted Array by the nth column:
[[3 1 6]
 [5 2 3]
 [1 4 2]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)


In [41]:

# Create a 2D array
array = np.array([[1, 0, 3], [0, 2, 0], [4, 0, 6]])

# Check if any column contains only zeros or NaN values
has_null_columns = np.any(np.all(array == 0, axis=0))

print("Does the array have null columns?", has_null_columns)


Does the array have null columns? False


#### 61. Find the nearest value from a given value in an array (★★☆)


In [43]:
def nearest_value(array, value):
    # Calculate the absolute differences between the value and each element of the array
    absolute_differences = np.abs(array - value)
    
    # Find the index of the element with the minimum absolute difference
    nearest_index = np.argmin(absolute_differences)
    
    # Get the nearest value
    nearest_value = array[nearest_index]
    
    return nearest_value

# Example array
array = np.array([1, 3, 5, 7, 9])

# Given value
value = 11

# Find the nearest value from the given value in the array
nearest = nearest_value(array, value)

print("Array:", array)
print("Given value:", value)
print("Nearest value:", nearest)


Array: [1 3 5 7 9]
Given value: 11
Nearest value: 9


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)


In [44]:
# Create two arrays with shapes (1,3) and (3,1)
array1 = np.array([[1, 2, 3]])
array2 = np.array([[4], [5], [6]])

# Initialize the sum
total_sum = 0

# Iterate over the elements of both arrays and compute the sum
iterator = np.nditer([array1, array2], flags=['multi_index'])
while not iterator.finished:
    total_sum += iterator[0]
    iterator.iternext()

print("Sum of the two arrays:", total_sum)

Sum of the two arrays: 18


#### 63. Create an array class that has a name attribute (★★☆)


In [45]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name=None):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj

# Create an instance of the NamedArray class with a name attribute
arr = NamedArray([1, 2, 3], name="MyArray")

# Access the name attribute
print("Name of the array:", arr.name)

# Test if it's a NamedArray instance
print("Is it a NamedArray instance?", isinstance(arr, NamedArray))


Name of the array: MyArray
Is it a NamedArray instance? True
