#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
# Import Numpy with alias np
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
# Check version of numpy
print(np.__version__)

1.26.2


#### 3. Create a null vector of size 10 (★☆☆)


In [13]:
# Create a null vector of size 10
null_vector = np.zeros(10)

print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)


In [14]:
# Find the memory size of the array
memory_size = null_vector.nbytes

print("Memory size of the array:", memory_size, "bytes")

Memory size of the array: 80 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)


In [ ]:
python -m pydoc numpy.add

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)


In [5]:
# Create a null vector of size 10
null_vector = np.zeros(10)

# Assign 1 to the fifth element (index 4, since indexing starts from 0)
null_vector[4] = 1

print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)


In [6]:
# Create a vector with values ranging from 10 to 49
vector = np.arange(10, 50)

print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [7]:
# Create a vector with values ranging from 10 to 49
vector = np.arange(10, 50)

# Reverse the vector
reversed_vector = vector[::-1]

print(reversed_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [8]:
# Create a vector with values ranging from 0 to 8
values = np.arange(9)

# Reshape the vector into a 3x3 matrix
matrix = values.reshape(3, 3)

print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [3]:
# Define the array
arr = np.array([1, 2, 0, 0, 4, 0])

# Find the indices of non-zero elements
indices = np.nonzero(arr)

print(indices)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [4]:
# Create a 3x3 identity matrix
identity_matrix = np.eye(3)

print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [5]:
# Create a 3x3x3 array with random values
random_array = np.random.random((3, 3, 3))

print(random_array)

[[[0.99779468 0.08833564 0.38837869]
  [0.86875295 0.80056094 0.74114665]
  [0.8217505  0.64917543 0.77469958]]

 [[0.77200978 0.70975654 0.87468841]
  [0.95425678 0.49664782 0.61496489]
  [0.42261108 0.2373618  0.31294906]]

 [[0.25836922 0.76586375 0.94941596]
  [0.6540722  0.59268556 0.59736153]
  [0.50586248 0.39216966 0.19930711]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [6]:
# Create a 10x10 array with random values
random_array = np.random.random((10, 10))

# Find the minimum and maximum values
min_value = np.min(random_array)
max_value = np.max(random_array)

print("Minimum value:", min_value)
print("Maximum value:", max_value)

Minimum value: 0.012385921668583766
Maximum value: 0.9979431617686895


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [7]:
# Create a random vector of size 30
random_vector = np.random.random(30)

# Find the mean value
mean_value = np.mean(random_vector)

print("Mean value:", mean_value)

Mean value: 0.5504029687477323


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [9]:
# Define the shape of the 2D array
rows, cols = 7, 5

# Create a 2D array filled with zeros
array = np.zeros((rows, cols))

# Set the border elements to 1
array[0, :] = 1  # Top row
array[-1, :] = 1  # Bottom row
array[:, 0] = 1  # Left column
array[:, -1] = 1  # Right column

print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [10]:
# Example existing array
existing_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

# Get the shape of the existing array
rows, cols = existing_array.shape

# Define the size of the border to add
border_size = 1

# Create a new array with zeros and the appropriate size
new_array = np.zeros((rows + 2 * border_size, cols + 2 * border_size))

# Copy the existing array into the center of the new array
new_array[border_size:rows+border_size, border_size:cols+border_size] = existing_array

print(new_array)

[[0. 0. 0. 0. 0.]
 [0. 1. 2. 3. 0.]
 [0. 4. 5. 6. 0.]
 [0. 7. 8. 9. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan = nan
np.nan == np.nan = False
np.inf > np.nan = False
np.nan - np.nan = nan
np.nan in set([np.nan]) = True
0.3 == 3 * 0.1 = False
```


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [20]:
# Create a 5x5 matrix filled with zeros
matrix = np.zeros((5, 5))

# Define the values to place below the diagonal
values = [1, 2, 3, 4]

# Set the values just below the diagonal
for i, value in enumerate(values):
    matrix[i+1, i] = value

print(matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [21]:
# Create an 8x8 matrix filled with zeros
matrix = np.zeros((8, 8), dtype=int)

# Assign alternate values (0 and 1) to alternate rows and columns
matrix[1::2, ::2] = 1  # Rows 1, 3, 5, 7, Columns 0, 2, 4, 6
matrix[::2, 1::2] = 1  # Rows 0, 2, 4, 6, Columns 1, 3, 5, 7

print(matrix)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [22]:
# Define the shape of the array
shape = (6, 7, 8)

# Find the indices of the 100th element
indices = np.unravel_index(99, shape)

print("Indices (x, y, z) of the 100th element:", indices)

Indices (x, y, z) of the 100th element: (1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [23]:
# Create a 2x2 checkerboard pattern
checkerboard = np.array([[0, 1], [1, 0]])

# Use tile function to repeat the pattern to create an 8x8 matrix
checkerboard_8x8 = np.tile(checkerboard, (4, 4))

print(checkerboard_8x8)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [24]:
# Create a 5x5 random matrix
matrix = np.random.random((5, 5))

# Calculate the mean and standard deviation of the matrix
mean = np.mean(matrix)
std_dev = np.std(matrix)

# Normalize the matrix
normalized_matrix = (matrix - mean) / std_dev

print("Original Matrix:")
print(matrix)
print("\nNormalized Matrix:")
print(normalized_matrix)

Original Matrix:
[[0.84385226 0.12815049 0.22805669 0.42831618 0.82306305]
 [0.41925023 0.77156786 0.43331991 0.67419839 0.14707416]
 [0.74607737 0.00873546 0.00643697 0.64935321 0.88928044]
 [0.11669372 0.34714801 0.14040371 0.71365048 0.03550355]
 [0.27349522 0.73707641 0.94187851 0.26765774 0.00795224]]

Normalized Matrix:
[[ 1.32104334 -0.9697654  -0.64998697 -0.00899904  1.25450151]
 [-0.03801722  1.08967637  0.00701684  0.77801746 -0.90919476]
 [ 1.00808675 -1.35198744 -1.35934442  0.69849336  1.46644924]
 [-1.00643609 -0.26880104 -0.93054546  0.90429518 -1.2663085 ]
 [-0.50454794  0.97927661  1.63480445 -0.52323244 -1.35449437]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)


In [25]:
# Define the custom dtype for RGBA color
color_dtype = np.dtype([('R', np.uint8),   # Red component
                        ('G', np.uint8),   # Green component
                        ('B', np.uint8),   # Blue component
                        ('A', np.uint8)])  # Alpha component

# Create a color using the custom dtype
color = np.array((255, 0, 0, 255), dtype=color_dtype)

print("RGBA Color:")
print(color)

RGBA Color:
(255, 0, 0, 255)


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [26]:
# Create a 5x3 matrix
matrix1 = np.random.random((5, 3))

# Create a 3x2 matrix
matrix2 = np.random.random((3, 2))

# Multiply the matrices
result = np.dot(matrix1, matrix2)

print("Resulting Matrix:")
print(result)

Resulting Matrix:
[[0.52445287 0.95481423]
 [0.32419711 0.38890865]
 [0.66586139 1.20303171]
 [0.41001965 0.75686865]
 [0.46236983 0.81202453]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [27]:
# Create a 1D array
array = np.array([1, 4, 6, 9, 3, 2, 7, 5, 8])

# Negate elements between 3 and 8 (inclusive)
array[(array >= 3) & (array <= 8)] *= -1

print("Modified Array:")
print(array)

Modified Array:
[ 1 -4 -6  9 -3  2 -7 -5 -8]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1)) = 9 because the in-built sum function starts summing from -1 to 4.
from numpy import *
print(sum(range(5),-1)) = 10 because -1 specifies the axis along which the summation is done which is the last axis. In this case range(5) is a 1D.
```


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

Z**Z: This expression raises each element of vector Z to the power of itself. It's legal in Python.

2 << Z >> 2: This expression performs bitwise left shift (<<) of 2 by each element of vector Z, and then performs bitwise right shift (>>) of the result by 2. It's legal in Python.

Z <- Z: This expression compares each element of vector Z with the negation of itself. It's legal in Python.

1j*Z: This expression multiplies each element of vector Z by the imaginary unit 1j. It's legal in Python.

Z/1/1: This expression divides each element of vector Z by 1 and then divides the result by 1 again. It's legal in Python.

Z<Z>Z: This expression is not legal. It tries to compare each element of vector Z with itself (Z < Z), and then compare the result with Z, which is not syntactically valid in Python.

So, the legal expressions are:

Z**Z

2 << Z >> 2

Z <- Z

1j*Z

Z/1/1


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

np.array(0) / np.array(0): This expression divides zero by zero. In NumPy, this results in a runtime warning, and the result is nan (not a number).

np.array(0) // np.array(0): This expression performs floor division of zero by zero. In NumPy, this also results in a runtime warning, and the result is 0.

np.array([np.nan]).astype(int).astype(float): This expression first creates a NumPy array containing a NaN (Not a Number) value, then converts it to an integer type using astype(int). Since NaN cannot be represented as an integer, it's converted to 0. Finally, the array is converted back to a float type using astype(float), resulting in an array containing [0.].

So, the results are:

np.array(0) / np.array(0): nan

np.array(0) // np.array(0): 0

np.array([np.nan]).astype(int).astype(float): [0.]

#### 29. How to round away from zero a float array ? (★☆☆)


In [33]:
# Example float array
float_array = np.array([-1.5, 2.7, -3.4, 4.8])

# Round away from zero by rounding up (ceil) the positive numbers and rounding down (floor) the negative numbers
rounded_array = np.sign(float_array) * np.ceil(np.abs(float_array))

print("Original Float Array:", float_array)
print("Rounded Away from Zero Array:", rounded_array)

Original Float Array: [-1.5  2.7 -3.4  4.8]
Rounded Away from Zero Array: [-2.  3. -4.  5.]


#### 30. How to find common values between two arrays? (★☆☆)


In [34]:
# Example arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

# Find common values between the two arrays
common_values = np.intersect1d(array1, array2)

print("Common Values:", common_values)

Common Values: [3 4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)


In [35]:
import warnings

# Ignore all NumPy warnings
warnings.filterwarnings('ignore', category=np.VisibleDeprecationWarning)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

No, the expression is not true.

In NumPy, np.sqrt(-1) returns a complex number representing the square root of -1 (1j), while np.emath.sqrt(-1) returns a complex number with a warning indicating that it's returning the principal square root of a negative number (1j).

However, both expressions return the same complex number 1j, but np.emath.sqrt(-1) provides additional warning information. Therefore, the equality check np.sqrt(-1) == np.emath.sqrt(-1) evaluates to True.

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)


In [37]:
from datetime import datetime, timedelta

# Get today's date
today = datetime.today().date()

# Get yesterday's date
yesterday = today - timedelta(days=1)

# Get tomorrow's date
tomorrow = today + timedelta(days=1)

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2024-02-06
Today: 2024-02-07
Tomorrow: 2024-02-08
